define({
	TheHubName: "Th'Hub",
    Desktops: "Desktops",
    WidgetLaunchAppmode: "Hoist th' sails",
    WidgetSettings: "Configger me widget",
    WidgetSubmitBug: "Avast! An er'",
    WidgetHelp: "Confer th' compass",
    WidgetRemove: "Abandon Ship!",
    WidgetHelpModalTitle: "Widget Compass: ",
    ConfigHeaderTitle: "Widget Configgerments",
    NavSearchPlaceholder: "Thar be me booty!",
    NavSearchWidgetGroup: "Me Grog",
    NavSearchServiceGroup: "Me Doubloons",
    NavSearchSearchEMC: "Walk de' plank to anoder domain",
    SearchResultAdd: "Add plunder to me booty",
    SearchResultAppmode: "Fire ye plunder to app mode",
    AlertMenuTitle: "Swags",
    AlertMenuManageSubscriptions: "Manage me sweet trade",
    AlertMenuManageSubscriptionsTitle: "Manage me sweet trade",
    AlertMenuClearList: "Off w't ya swashbucklin scallywags",
    AlertMenuViewAll: "See all scallywags",
    AlertMenuViewAllTitle: "all scallywags",
    AlertDismiss: "Walk de' plank",
    ReleaseNotesTitle: "sweet trade",
    CreateIncidentTitle: "Avast! an er' to report",
    RequestEnhancementTitle: "Idea hole",
    FAQTitle: "Buccaneers",
    CloseAppmodeBtnTitle: "Abandon ship!",
    DeepLinkAppmodeBtnTitle: "link me' to me booty",
    LivewireTrigger: "Buccaneer hangout",
    AlertSaveErrorMsg: "Avast! Yer booty has been plundered by th' backend!",
    DesktopSaveFailure: "Avast! Yer booty has been plundered by th' backend!",
    SharedDesktopLink: "sweet trade fer me plunder",
    CreateNewDesktop: "Create me desktop",
    SharedDesktopsTitle: "Desktops for me buccaneers",
    NewDesktopPlaceholder: "Argh!",
    DesktopCreateTooltip: "Create me new desktop for ye landlubbers",
    DesktopCancelTooltip: "Avast!",
    DesktopCreateErrorMessage: "Avast! Yer booty has been plundered by th' backend!",
    DesktopOptionRename: "Rename me booty",
    DesktopOptionDelete: "Abandon me plunder",
    DesktopOptionShare: "Share me scurvy desktop",
    DesktopOptionClone: "Clone me plunder!",
    CloneSwitchTitle: "High-tale to anoder ship",
    CloneSwitchMessage: "Yer desktop booty has been cloned, would ye like to high-tale der now?",
    CloneFailure: "Avast! Yer booty has been plundered by th' backend!",
    CloneSwitchYes: "High-tale to anoder desktop",
    CloneSwitchNo: "Keep th' course",
    DesktopRenameTooltip: "Rename me furner",
    DesktopRenameCancel: "Cancel me furner",
    DesktopRenameFailure: "Avast! Yer booty has been plundered by th' backend!",
    ShareDesktopModalTitle: "Scurvy me buscuits, ye' wish to share yer booty!?",
    LastDesktopDeleteError: "Well son of a buscuit eater, ya cant overboard ye only ship!",
    DeleteDesktopError: "Avast! Yer booty has been plundered by th' backend: ",
    ConfirmationTitle: "Confirm ye landlubber!",
    DeleteDesktopConfirmMessage: "Abandon furner: '{{ Name }}', ye sure?",
    Delete: "Walk de plank",
    Cancel: "Stop me foolishness",
    EmptyAlertsMessage: "Ther be no new booty here, scallywag",
    MyInformationTitle: "Me Squadron o' furners",
    ConfigureWidgetModalTitle: "Configger",
    DeepLinkFailure: "Avast! Yer booty has been plundered by th' backend!",
});